- name: Demo on conditions
  hosts: all
  gather_facts: yes
  tasks:
   - name: Run on CentOS
     shell: yum makecache
     when: ansible_distribution == "CentOS"


   - name: Run on Ubuntu
     shell: apt-get update
     when: ansible_distribution == "Ubuntu"


   - name: Run on RedHat
     shell: yum makecache
     when: ansible_distribution == "RedHat"


   - name: Check load average
     shell: "uptime | awk -F : '{print $NF}' | awk -F , '{print $1}' | awk -F . '{print $1}' | sed -s 's/ //g'"
     register: out

   - name: Print load average
     debug: 
       var: out.stdout_lines
     

   - name: Send Load Average to slack
     when: out.stdout == 0
     slack:
      token: TS46SULA2/BRRP0LJU9/1G5dtRDrpnSX3MnNfGxFufcF
      msg: "Hello"

## Check file status

- name: Check file exist or not
  hosts: all
  gather_facts: false
  tasks:
    - name: Check test.txt exist or not
      stat:
        path: /tmp/test.txt
      register: status
    - debug: var=status   

- name: Create file if not exist
  hosts: all
  file:
    state: touch
    path: /tmp/test.txt
    owner: root
    group: root
    mode: 0755
  when: status.stat.exists == false 
