- name: Demo on conditions
  hosts: all
  gather_facts: yes
  tasks:
   - name: Run on CentOS
     shell: yum makecache
     when: ansible_distribution == "CentOS"


   - name: Run on Ubuntu
     shell: apt-get update
     when: ansible_distribution == "Ubuntu"


   - name: Run on Ec2-user
     shell: apt-get update
     when: ansible_distribution == "Ec2-user"