- name: Demo on conditions
  hosts: all
  gather_facts: yes
  tasks:
   - name: Run on CentOS
     shell: yum makecache
     when: ansible_distribution == "CentOS"


   - name: Run on Ubuntu
     shell: apt-get update
     when: ansible_distribution == "Ubuntu"


   - name: Run on Ec2-user
     shell: apt-get update
     when: ansible_distribution == "Ec2-user"


   - name: Check load average
     shell: "uptime | awk -F : '{print $NF}' | awk -F , '{print $1}' | awk -F . '{print $1}' | sed -s 's/ //g'"
     register: out

   - name: "Print load average"
     debug: "Load Average = {{out.stdout}}"
     

   - name: Send Load Average to slack
     when: out.stdout > 1
     slack:
      token: TS46SULA2/BRRP0LJU9/1G5dtRDrpnSX3MnNfGxFufcF
      msg: "Hello"
