- name: Demo on standard loops
  hosts: all
  tasks:
   - name: Print multipls values
     debug:
      msg: "Hell0 , {{item}}"
     loop:
      - Keishna
      - Radhe
      - Mohan

## Above example is for a simple list.

- name: Demo is standard loops for hash
  hosts: all
  tasks:
   - name: Print hash value
     debug:
      msg: "Hello {{item.name}} , your email is {{item.email}}"
     loop:
      - {name: "Krishna", email: "krishna@gmail.com"}
      - {name: "Radhe", email: "radhe@gmail.com"}

- name: Install vsftpd and tree
  hosts: all
  tasks:
    - name: "Installing VSFTPD"
      apt: name="vsftpd" stat="present"
    - name: "Installing tree"
      apt: name="tree" stat="present"
      