- name: Check file exist or not
  hosts: all
  gather_facts: false
  tasks:
    - name: Check test.txt exist or not
      stat:
        path: /tmp/test.txt
      register: status_result
    - debug:
        msg: "File exist"
      when: status_result.stat.exists
    
    - debug:
        msg: "File does not exist"
      when: status_result.stat.exists == false

    - name: Create File if not exist
      file:
        state: touch
        path: /tmp/test.txt
    - debug:
        msg: "File created"
      when: status_result.stat == false 

## Now Check dir is exist or not

- name: check test dir
  hosts: all
  tasks:
    - name: Check dir exist or not
      stat:
        path: /tmp/test
      register: dir_status
    - debug:
        msg: "Dir exist"
      when: dir_status.stat.exists == true

    - debug: 
        msg: dir does not exist
      when: dir_status.stat.exists == false

    - name: create test dir
      command: mkdir -p /tmp/test
    - debug:
        msg: "Test dir created"
      when: dir_status.stat.exists == false



- name: Print info about my play
  hosts: all
  gather_facts: flase
  tasks:
    - name: print hostsname
      debug:
        msg: "it's me , {{ ansible_hostname }}"   



##Write a playbook to install ‘zlib’ and ‘vim’ on all hosts if the file ‘/tmp/mario’ exists on the system

- name: check mario file exist or not
  hosts: all
  tasks:
    - name: Check file status
      stat:
        path: /tmp/mario
      register: mario_status
    - debug:
        msg: "Mario file does not exist"
      when: mario_status.stat.exist == false

    - name: Create Mario file
      stat:
        path: /tmp/mario
        state: present
    - debug:
        msg: "File created"
      when: mario_status.stat.exist == true







     


