## Check file status

- name: Check file exist or not
  hosts: all
  gather_facts: false
  tasks:
    - name: Check test.txt exist or not
      hosts: all
      stat:
        path: /tmp/test.txt
      register: status_result
    - debug:
        msg: "File exist"
      when: status_result.stat.exists == true

    - debug:
        msg: "File does not exist"
      when: status_result.stat == false  


