## Check file status

- name: Check file exist or not
  hosts: all
  gather_facts: false
  tasks:
    - name: Check test.txt exist or not
      stat:
        path: /tmp/test.txt
      register: status
    - debug: var=status   



- name: "Create file if not exist"
  hosts: all
  file:
    state: touch
    path: /tmp/test.txt
    
  when: status.stat.exists == false 