- name: "Add multiple users"
  hosts: all
  become: yes
  become_user: root
  user: 
    name: "{{ item }}"
    state: present
    groups: root
  with_items:
      - krishna
      - guddu
      - shyam
