- name: Demo on Run time variables
  hosts: all
  tasks:
   - name: Declare a variable with set_fact module
     set_fact:
      URL: google.com

- name: Access the variables from previous task
  debug:
   msg: "URL = {{URL}}"