- name: Demo on Run time variables
  hosts: all
  tasks:
   - name: Get load average
     shell: uptime
     register: out

   - name: Declare a variable with set_fact module
     set_fact:
      URL: google.com
      LOAD: "{{out.stdout.split(':') | last.split('=')}}"

- name: Access the variables from previous task
  hosts: all
  tasks:
   - name: Acess variable from previous task
     debug:
      msg: "URL = {{URL}}, load average = {{LOAD}}"