- name: Install the latest version of httpd
  yum:
    name: httpd
    state: latest



- name: Copy proxy file
  copy:
    src: proxy.conf
    dest: /etc/httpd/conf.d/proxy.conf

- name: Download index URL
  get_url:
    url: "{{INDEX_URL}}"
    dest: /var/www/html/index.html


- name: restart httpd service
  service:
    name: httpd
    state: started
    enabled: yes